"""cleanup Confidence enum

Revision ID: 2863ebb50b21
Revises: 3eec6b2b25dc
Create Date: 2026-08-18 18:55:40.443476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2863ebb50b21'
down_revision: Union[str, Sequence[str], None] = '3eec6b2b25dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
