"""add technique catalog and ratings

Revision ID: dcd9a77f9298
Revises: 6961a07ac98b
Create Date: 2026-08-15 18:09:11.354341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd9a77f9298'
down_revision: Union[str, Sequence[str], None] = '6961a07ac98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('techniques',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techniques_category_id'), 'techniques', ['category_id'], unique=False)
    op.create_table('technique_ratings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('confidence', sa.Enum('L', 'M', 'H', name='confidence'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_technique_rating_rating_range'),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'technique_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technique_ratings')
    op.drop_index(op.f('ix_techniques_category_id'), table_name='techniques')
    op.drop_table('techniques')
    op.drop_table('categories')
    # ### end Alembic commands ###
